### ISSUE TITLE
Rust version parsing error: `invalid literal for int() with base 10: '3-beta'`

### ISSUE THREAD

**Issue by tushar-deepsource** [deepsourcelabs/depend#55]
```
Traceback (most recent call last):
  File "/Users/tusharsadhwani/code/depend/src/depend/resolver.py", line 253, in _make_multiple_requests
    resolved_deps = await asyncio.gather(*resolved_vers)
  File "/Users/tusharsadhwani/code/depend/src/depend/resolver.py", line 65, in make_single_request
    version_constraints = fix_constraint(language, version)
  File "/Users/tusharsadhwani/code/depend/src/depend/dependencies/helper.py", line 397, in fix_constraint
    [
  File "/Users/tusharsadhwani/code/depend/src/depend/dependencies/helper.py", line 398, in <listcomp>
    fix_constraint_rust(constraint)
  File "/Users/tusharsadhwani/code/depend/src/depend/dependencies/helper.py", line 415, in fix_constraint_rust
    fixed_constraint = handle_caret(fixed_constraint)
  File "/Users/tusharsadhwani/code/depend/src/depend/dependencies/helper.py", line 536, in handle_caret
    limit = f"0.0.{int(patch) + 1}"
ValueError: invalid literal for int() with base 10: '3-beta'
```

**Comment by NobleMathews** [comment]
Occurs due to the following logic which is used to handle caret as well as tilde
`major, minor, patch, *_ = (version + "...").split(".")`
Adding a line to ignore hyphenated sections, should still be a valid constraint
